version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "Gym"
      MYSQL_ROOT_PASSWORD: "qazwsx123"
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/Gym?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=qazwsx123
      - spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - spring.thymeleaf.enabled=true
